### ISSUE TITLE
JPA

### ISSUE THREAD

**Issue by autarchprinceps** [autarchprinceps/Conference-System#11]
Ich verstehe ein paar Sachen an den Entityklassen nicht:

Warum lagerst du manche Infos in eine eigene Klasse mit Suffix PK aus? Wann füge ich neue Daten in die PK Klasse und wann in die eigentliche Entity?

Du hast z.B. in Publication und Review einerseits die authorId und die conferenceId, aber auch die Entities Conference und User und du setzt beim erstellen beides manuell auf das gleiche. Sind das nicht redundante Daten? Sollte man nicht vielleicht zum Beispiel nur die Conference speichern. Wenn man die Id der Conference braucht, kann man dann ja .getConference().getId() machen.

**Comment by MBasti** [comment]
Ich habe alles, bis auf einige Anpassungen, von Netbeans erstellen lassen. Die PK-Klassen sind nicht meine Idee und werden bei zusammengesetzten Fremdschlüssen erstellt, also kommen da nach meinem Verständnis auch nur die Schlüsselattribute rein.

> Du hast z.B. in Publication und Review einerseits die authorId und die conferenceId, aber auch die Entities Conference und User und du setzt beim erstellen beides manuell auf das gleiche.

Ja die Felder sind doppelt, das hat auch Netbeans/JPA so gemacht und ich dachte, dass das aus irgendwelchen Gründen so seine Richtigkeit hat... Ich weiß nicht ob man beim erstellen der Objekte die Felder (also zb. authorId) überhaupt doppelt setzen muss, aber ich habe das zur Sicherheit so gemacht.

**Comment by autarchprinceps** [comment]
Hmm ok, wenn Netbeans das so vorgibt, wird das vielleicht Sinn machen, aber wenn wir das in einem Diagramm darstellen, würde ich es trotzdem ohne die PK Klassen darstellen, oder?

**Comment by MBasti** [comment]
Ja, nicht darstellen.
