### ISSUE TITLE
Participant Limit

### ISSUE THREAD

**Issue by autarchprinceps** [autarchprinceps/Conference-System#13]
Ich habe beim Erstellen einer Konferenz mit mehr als 200 Teilnehmern eine Mindestdurchschnittsbewertung von 0 (entspricht 3 Sternen) eingeführt.
Das war ja glaub ich eine Anforderung, aber ich habe keine Stelle finden können, an der die bislang umgesetzt wurde.

Dabei habe ich mich gefragt, ob wir eigentlich überprüfen, ob das Limit an Benutzern bereits erreicht ist, wenn ein neuer Nutzer sich registriert. Weißt du, ob wir das überprüfen?

**Comment by autarchprinceps** [comment]
Ich habe beides in der EJB hinzugefügt. Wenn die Bedingungen Fehlschlagen, werfe ich eine Exception, oder gibt es einen besseren Weg dem User mitzuteilen, dass das nicht geht.

**Comment by MBasti** [comment]
>Wenn die Bedingungen Fehlschlagen, werfe ich eine Exception, oder gibt es einen besseren Weg dem User mitzuteilen, dass das nicht geht.

Reicht doch. Die Exceptions werden abgefangen und dem User wird eine wenig hilfreiche Fehlermeldung angezeigt.
