### ISSUE TITLE
Administrate your Account

### ISSUE THREAD

**Issue by autarchprinceps** [autarchprinceps/Conference-System#14]
Wir haben noch eine fehlende Region in UserView. Was soll da alles rein? Was ist nicht zu schwer zu implementieren?

Ich würde sagen Passwort änderen ist definitiv möglich. Soll man den Accountnamen ändern können? Ich glaube das wäre technisch möglich, da der Primärschlüssel ja die ID ist und nicht der Name.
Account löschen könnte problematisch sein, oder glaubst du das geht einfach?
Deregister from Conference haben wir ja schon an anderer Stelle.
Sonst fällt mir nichts mehr ein. Dir?

**Comment by MBasti** [comment]
Letztendlich ist Account löschen auch kein Problem. Man muss halt alles kaskadieren. Die Frage ist eher, ob man Lust hat irgendwelche Dialoge umzusetzen. Ich denke eine Sache wie Passwort oder Name ändern reicht.
