### ISSUE TITLE
JDBC-Konfiguration

### ISSUE THREAD

**Issue by MBasti** [autarchprinceps/Conference-System#5]
Aus irgendeinem Grund wird die glassfish-ressources.xml ignoriert, nicht richtig akzeptiert oder ist halt verbuggt. Es bringt auch nichts ein neues Projekt zu öffnen. Wie gesagt habe ich auch mit anderen Gesprochen die das gleiche Problem haben. Insofern können wir jdbc derzeit nur manuell konfigurieren (siehe Bild). Wenn du das auch so konfigurierst, solltest du die Anwendung "deployen" können.

Für den Zugriff auf die DB muss natürlich VPN aktiviert sein und ich habe schonmal Entity-Klassen erstellen lassen. Ich weiß jetzt grade aber noch nocht, ob Anfragen überhaupt funktionieren (da noch keine Bean soweit implementiert ist).

![jdbc-config](https://cloud.githubusercontent.com/assets/7253991/5739180/36d42750-9bf6-11e4-8f05-8234f5518faf.PNG)

**Comment by autarchprinceps** [comment]
Heißt das, dass man das an jeden Rechner neu machen muss, weil es nicht vernünftig mit eingecheckt wird?

**Comment by MBasti** [comment]
Naja zumindest immer wenn Netbeans gestartet wird. Man kann aber auch die Ressource gleich in 
.../glassfish/domains/domain1/config/domain.xml 
definieren:

     <jdbc-resource enabled="true" jndi-name="jdbc/ooka-postgresql" pool-name="DerbyPool" object-type="user">
            <property name="serverName" value="dumbo.inf.h-brs.de"/>
            <property name="databaseName" value="bmager2s"/>
            <property name="User" value="bmager2s"/>
            <property name="Password" value="bmager2s"/>
            <property name="URL" value="jdbc:postgresql://dumbo.inf.h-brs.de/bmager2s"/>
            <property name="driverClass" value="org.postgresql.Driver"/>
        </jdbc-resource>

Dann startet der Server gleich mit der Ressource und man muss nix manuell eintragen. Hätte ja gerne gesehen, wie der Alda das konfiguriert, aber soweit ist es ja nicht gekommen...

**Comment by autarchprinceps** [comment]
Ich habe das jetzt mehrmals probiert, aber ich kriege es nicht hin.
Die Persistenz weigert sich zu starten, egal ob ich die Datenbank nehme, die du schon hinzugefügt hast, oder versuche eine eigene anzulegen.
Ich kriege immer das gleiche: org.glassfish.deployment.common.DeploymentException: Invalid resource : jdbc/ooka-postgresql__pm

Ich kann auch schlecht irgendwas debuggen, wenn das nicht funktioniert.
Hast du irgendeine Ahnung, was hier falsch läuft?

**Comment by autarchprinceps** [comment]
Ach übrigens das liegt nicht an Postgresql, Derby macht genau das gleiche

**Comment by MBasti** [comment]
Hast du mal versucht unter .../glassfish/domains/domain1/config/domain.xml ne Ressource manuell anzulegen? Ich arbeite derzeit mit ner lokalen derby db, aber es kommt keine Fehlermeldung und man kann arbeiten. Ich hab das mittlerweile aufgegeben. Die Tabellen werden dann automatisch angelegt.

**Comment by autarchprinceps** [comment]
Ich habe Derby schon ausprobiert. Ich habe den Connection Pool und die Datasource in der domain.xml, graphisch in Netbeans und auch in der Glassfish Admin Console versucht anzulegen, aber es kommt immer Invalid resource.

**Comment by autarchprinceps** [comment]
Muss ich vorher irgendwie eine Datenbank anlegen, oder was mach ich falsch?

**Comment by MBasti** [comment]
Es existieren ja irgendwie default Datenbanken/Pools. Ich habe DerbyPool angegeben und dann funktionierte das.

**Comment by MBasti** [comment]
Also ich habe nur die eine Datasource angelegt. Die Datasource muss auch in der persistence.xml angegeben sein. Stimmt der Name dort überein?

**Comment by autarchprinceps** [comment]
In der persistence.xml kann ich nur Verbindungen auswählen, die ich tatsächlich angelegt habe.
Deshalb verstehe ich nicht, warum das funktioniert, das ist ja eigentlich graphisch.

**Comment by MBasti** [comment]
Funktionier das denn?

**Comment by autarchprinceps** [comment]
Nichts funktioniert bisher.
Im Internet finde ich nur Hinweise, dass da ja ein __pm angehängt wird, was vllt falsch ist.

**Comment by MBasti** [comment]
Die Fehlermeldung __pm kommt wenn die Ressource nicht existiert. Die Config-Dateien in Netbeans funtionieren nicht, oder müssen vllt. auch nur in ein anderes Projekt(?).

Also ich habe nur wie im 3. Post eine jdbc/ooka-postgresql Dataressource mit DerbyPool selbst angelegt. Der Name macht zwar keinen Sinn mehr, aber dann stimmt der mit der persistence.xml

**Comment by autarchprinceps** [comment]
Ja ich habe das natürlich als erstes mit deiner config ausprobiert, aber das macht das gleiche.

**Comment by autarchprinceps** [comment]
Hmm, ich habe es irgendwie hingekriegt, indem ich eine von den Beispieldatenbanken von Netbeans benutzt habe.
Keine Ahnung was bei den anderen falsch läuft, ich hoffe mal, das ich das so zumindest für etwas debuggen benutzen kann, aber es wäre nicht schlecht, wenn du das irgendwie mit Postgres zum laufen kriegen könntest, dann könnte man vllt Beispieldaten vorbereiten, um etwas zu zeigen, Derby ist ja eine rein lokale DB.

**Comment by MBasti** [comment]
Ja, mal gucken. Du siehst ja wie komisch das ist...

Aber man kann doch auch mit der lokalen DB was vorbereiten. Die Daten bleiben ja erhalten. Oder wie meinst du das?

**Comment by autarchprinceps** [comment]
Ich habe es nochmal mit einem lokalen Server versucht und laufe in das gleiche Problem.
Wenn die Datenbankverbindung nicht bei der Installation von Netbeans angelegt wurde, fehlt anscheinend noch etwas.
Es ist auch egal ob ich Postgres, MySQL oder Derby benutze.

**Comment by MBasti** [comment]
Also mit der Konfiguration die ich hochgeladen habe funktioniert es jetzt bei mir. Die Daten landen auch auf https://dumbo.inf.h-brs.de/phppgadmin/

**Comment by autarchprinceps** [comment]
Ich kriege eine neue Exception. Ich habe meinen VPN angemacht, aber es scheint, als ob er nicht auf die Datenbank kommt. Keine Ahnung warum, aber ich würde das nicht als Priorität ansehen, das liegt wahrscheinlich irgendwie an meiner Verbindung von zu hause zur Uni.

Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: Error in allocating a connection. Cause: Connection could not be allocated because: FATAL: no pg_hba.conf entry for host "91.55.46.205", user "bmager2s", database "bmager2s", SSL off

**Comment by MBasti** [comment]
Hast du's mal mit einer besseren Verbindung ausprobieren können?

**Comment by autarchprinceps** [comment]
Ich habe es mit einer lokalen PostgreSQL (und ja, die habe ich schon für andere Dinge benutzt, die funktioniert an sich) und auch einer lokalen Derby versucht. Der läuft immer in Probleme.

Ich kann es nur mit existierenden Beispieldatenbankverbindungen benutzen. Sobald ich eine neue mit Netbeans anlege, funktioniert es nicht.
