### ISSUE TITLE
Rating

### ISSUE THREAD

**Issue by autarchprinceps** [autarchprinceps/Conference-System#7]
Du hast die Anzahl von Sternen auf 6 reduziert. Kannst du mir erklären, wie das neue Rating funktioniert?

Bei doRate substrahierst du 6 von den momentanen Wert, also sind die möglichen Int-Werte -5 bis 0?
Das scheint mir etwas merkwürdig, was hast du dir dabei gedacht?

Du setzt averageRating außerdem auf das Rating des currentUser, das mach doch wenig Sinn oder?
Ich habe mal ein neues averageRating implementiert, aber soll ich das an der Stelle lassen, oder sollte das lieber in ein EJB oder in die Persistenz rein?

**Comment by autarchprinceps** [comment]
Der User kann seine Bewertung nicht abgeben, weil wenn er Sie noch nicht abgegeben hat, dann existiert anscheinend noch keine Bewertung in der currentConference.getConferenceRatingCollection()
Wenn Sie dort aber nicht existiert, dann schlägt ein .setRating mit NullPointerException fehl.
Wie erstellt man eine gänzlich neue Bewertung wenn noch keine existiert?

**Comment by MBasti** [comment]
>Du hast die Anzahl von Sternen auf 6 reduziert. Kannst du mir erklären, wie das neue Rating funktioniert?
>
>Bei doRate substrahierst du 6 von den momentanen Wert, also sind die möglichen Int-Werte -5 bis 0?
>Das scheint mir etwas merkwürdig, was hast du dir dabei gedacht?

Ich weiß nicht mehr warum und macht auch keinen Sinn für mich ^^

> Der User kann seine Bewertung nicht abgeben, weil wenn er Sie noch nicht abgegeben hat, dann existiert anscheinend noch keine Bewertung in der currentConference.getConferenceRatingCollection()
> Wenn Sie dort aber nicht existiert, dann schlägt ein .setRating mit NullPointerException fehl.
> Wie erstellt man eine gänzlich neue Bewertung wenn noch keine existiert?

Ja auf Null prüfen und ein Rating anlegen, oder wenn nicht Null das alte Rating ändern, würde ich sagen...

**Comment by autarchprinceps** [comment]
Ok, aber wie genau lege ich ein neues Rating an?

**Comment by MBasti** [comment]
Eigentlich funktioniert das Bewerten jetzt. Ich verstehe nur nicht was du hiermit machst:

> Math.round(confRatings.stream().map((conferenceRating) -> conferenceRating.getRating()).reduce((a, b) -> a + b).orElse(ratingCount * 3) / ratingCount);

**Comment by autarchprinceps** [comment]
Ich summiere alle Bewertungen auf und teile durch die Anzahl der Bewertungen. Das ist das ganz normale arithmetische Mittel oder wolltest du einen Median benutzen?

**Comment by MBasti** [comment]
Ok, aber warum dieses ratingCount *3 ?

**Comment by autarchprinceps** [comment]
Das ist nur der default Wert. Der sollte nie in den Fall reingehen, da wir ja ihn vorher überprüfen.
Ich gucke nachher mal, ob wir das noch brauchen. Es kann sein, dass, wenn ich das wegmache, ein try catch nötig wäre.
