### ISSUE TITLE
Konferenzersteller

### ISSUE THREAD

**Issue by autarchprinceps** [autarchprinceps/Conference-System#8]
So wie es im Moment ist, kann jeder Nutzer direkt nach der Registrierung auch seine eigene Konferenz erstellen.
Soll das so sein, oder brauchen wir da eine zusätzliche Berechtigung?

Ich weiß, dass man Konferenzen über 200 oder so Leute nur erstellen können sollte, wenn die Durchschnittsbewertung eine gewisse Mindesthöhe hat. Das meine ich nicht. Sollen allgemein Nutzer nach Konferenzbetreibern und Konferenzteilnehmern unterschieden werden, oder ist es so wie es jetzt ist deiner Meinung nach gut?

**Comment by MBasti** [comment]
Hab grad nochmal in die Anforderungen geschaut und nach meinem Verständnis ist das ok so.

Wenn du das aber haben möchtest, können wir das machen.

**Comment by MBasti** [comment]
Wobei... wie interpretierst du das ?:

> Verwenden sie das Rollenmodell der EJB zur Abbildung der Rollen auf ihre
> Applikation (vgl. Kapitel 5-1). Als Alternative können sie auch ein Rollenmodell
> basierend auf einer eigenen Implementierung realisieren.

**Comment by autarchprinceps** [comment]
Ich bin mir nicht sicher. Wenn ich in der Realität ein Konferenzverwaltungssystem bauen würde, würde ich das Problem lösen, indem Registrierungen nicht einfach automatisch angenommen würden, sondern von irgendeiner Person vllt überprüft wird.
Wenn zum Beispiel jemand sich bei einer Konferenz als Autor registriert, würde ich das an den Konferenzersteller weitergeben, damit der die Entscheidung trifft, aber das ist in diesem Projekt glaub ich nicht sinnvoll.

Durch die Begrenzung auf kleine Konferenzen, bis man ein Minimum an guten Bewertungen hat, könnte man durchaus argumentieren, dass man das so lassen kann, wenn du kein Problem damit hast, dass jeder Konferenzen erstellen kann. Es wäre natürlich auch nicht allzu schwer einen Nutzer von Anfang an als "kann Konferenzen erstellen" oder nicht zu markieren, aber da wir ja auch hier keinen Admin oder so was haben, der die Registrierung überprüft, könnte sich ja jeder User einfach als Konferenzersteller registrieren.

**Comment by autarchprinceps** [comment]
Wir sollten das vllt aber als eine der Designentscheidungen dokumentieren, dann kann er uns nicht vorwerfen, dass wir darüber nicht nachgedacht haben.

**Comment by MBasti** [comment]
> CR 1: Es soll eine wiederverwendbare Funktionalität bereit gestellt werden, mit der die
> Reputation eines Konferenzorganisators überprüft werden kann. Die Reputationsprüfung
> erfolgt auf der Grundlage alter Bewertungen zu abgeschlossenen Konferenzen. Falls
> eine „kritische Marke“ unterschritten, dann dürfen Konferenzen ab einer Teilnahmezahl
> von 200 Personen nicht mehr organisiert werden.

In der Übung (Übung 8) ist Wiederverwendbarkeit hervorgehoben. Das zielt wohl auf die Wiederverwendbarkeit von Komponenten ab. Ist unser Ding wiederverwendbar?

**Comment by autarchprinceps** [comment]
Hmm, also man kriegt die durchschnittliche Wertung ja aus der Search EJB. Sie ist also von einer anderen GUI oder einem System, dass nur auf unsere Daten zugreift, wiederverwendbar.
Gleiches gilt für die Überprüfung beim Erstellen einer Konferenz.
Aber es ist ja natürlich nicht unabhängig von den Entities. Ich meine er braucht ja Bewertungen um den Durchschnitt zu bilden.
Ich werde aus vielem, was der Alde schreibt, nicht so ganz schlau.

Ich meine wir können unser Bewertungsprinzip noch dokumentieren, aber sonst wüsste ich nicht, wie wir es besser machen soll.
