### ISSUE TITLE
Publikation

### ISSUE THREAD

**Issue by autarchprinceps** [autarchprinceps/Conference-System#9]
Die Publikation ist im Moment einfach Text. Wenn wir das durch sagen wir mal ein PDF-Dokument ersetzen wollen, was müsste alles angepasst werden?

Ich glaube:
Publication Entity
File Dialog in xhtml
Annahme und Weitergabe der Datei in ViewController Managed Bean

**Comment by MBasti** [comment]
Ja, es fehlt eigentlich dass eine Publikation mehrere Revisionen haben kann oder?

**Comment by autarchprinceps** [comment]
Stimmt, aber das ist ein eigenes Problem und sollte eigentlich unabhängig vom Format einer einzelnen Revision sein.

**Comment by autarchprinceps** [comment]
Ich habe den File Dialog mal hinzugefügt, aber ich weiß nicht was ich alles machen muss, sodass in der Publication Entity statt String text; List<byte[]> revisions; stehen kann.
Kann ich das einfach ersetzen, oder was muss ich da noch ändern?

**Comment by MBasti** [comment]
Der Datentyp ist dann ein Blob? Für ne Liste bräuchte man eigenlich dann noch eine Revision Entity-Klasse damit das auf Tabellen abgebildet wird. Wie bei anderen Collections/List auch.

**Comment by MBasti** [comment]
Autoren können jetzt sequentiell neue Revisionen hochladen (im PubView, nicht im createView). Es fehlen noch Download-Links für die Reviews.

**Comment by autarchprinceps** [comment]
Download funktioniert jetzt bei mir.

Ich weiß, dass der Reviewer keine Revisionen seiner Reviews hat, aber die Reviews sollten wahrscheinlich auch Dateien sein. Ich weiß nicht ob du entsprechende Änderungen in der JPA schon gemacht hast. Ich werde später heute oder morgen die UI dafür erstellen/apassen. Ich glaube, wenn du das noch nicht gemacht hast, dass ich die JPA dafür aber auf Basis der Publikationsentityklasse wahrscheinlich selber anpassen kann. Wenn nicht frage ich dich noch mal.

**Comment by MBasti** [comment]
Ne, hatte ich noch nicht gemacht, aber eigentlich muss man da nur den Datentypen von String auf byte[] überall ändern mit den entsprechenden Anotationen (wie in PublicationRevision). Es kann sein, dass man die Tabelle Review in der DB dann löschen muss, wenn man was in der Entity ändert (bin ich mir grad nicht sicher).

 **Noch was:**

1. Du hast filename und contenttype noch in *PublicationRevisionPK* getan. Also JPA macht für zusammengesetzte Primärschlüssel eine eigene Klasse und die 2 neuen Felder gehören für mich jetzt nicht zum Primärschlüssel, was aber anscheinend praktisch keinen Unterschied macht. Wollte ich nur anmerken.

2. Wie sollen wir diese Anforderung umsetzen?
> FA3: Zuordnung Paper zu Gutachter durch den Organisator der Konferenz

**Comment by autarchprinceps** [comment]
1. Habe ich mit Commit Review behoben.

2. Hmm ok, im Moment kann jeder Reviewer einer Konferenz alle Paper ohne Einschränkungen reviewen. Glaubst du wir brauchen da noch eine zusätzliche Einschränkung?
Falls ja müsste der Organisator einer Konferenz wahrscheinlich im PubView aus einer Liste der Reviewer mit Checkbox diejenigen auswählen, die reviewen sollen/können. Und wir müssten den check für das Uploaden eines Reviews von isReviewer auf isReviewerOfPublication ändern.
Ich bin mir nicht sicher was das für Konsequenzen für das JPA hat. Wahrscheinlich eine neue OneToMany-Beziehung in Publication: Collection<User> authorizedReviewers; oder so.

**Comment by autarchprinceps** [comment]
zu 2. Ich fände das eigentlich etwas umständlich, ich meine dann müsste der Organizer ja durch jede Publication durchgehen und die Reviewer auswählen. In der Realität wäre das glaub ich übermäßig aufwendig, aber das heißt nicht, dass unser Prof das nicht als Anforderung gesetzt haben könnte.

**Comment by MBasti** [comment]
Naja, da das offensicht leider eine Anforderung ist, werde ich mal anfangen das umzusetzen.
